# Generated by Django 3.1.6 on 2021-03-10 10:58

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('wouri', 'Wouri'), ('nkam', 'Nkam'), ('sanaga-maritime', 'Sanagamaritime'), ('moungo', 'Moungo')], default='wouri', max_length=50)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.SlugField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=30)),
            ],
            options={
                'ordering': ('-publish',),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
