# Generated by Django 3.1.6 on 2021-03-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210310_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local_stats',
            new_name='Local_stat',
        ),
    ]
