# Generated by Django 3.1.6 on 2021-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDS', '0002_auto_20210317_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableau_de_synthese',
            name='wouri',
        ),
        migrations.RemoveField(
            model_name='tableau_de_synthese',
            name='zone_a',
        ),
        migrations.AddField(
            model_name='tableau_de_synthese',
            name='department',
            field=models.CharField(choices=[('wouri', 'Wouri'), ('nkam', 'Nkam'), ('sanaga-maritime', 'Sanaga Maritime'), ('moungo', 'Moungo')], default=None, max_length=50),
        ),
    ]
