# Generated by Django 3.1.6 on 2021-03-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TDS', '0003_auto_20210317_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='magic',
        ),
    ]
