# Generated by Django 3.1.6 on 2021-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDS', '0004_delete_magic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableau_de_synthese',
            name='Semestre',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=20),
        ),
    ]
