# Generated by Django 3.1.6 on 2021-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDS', '0005_tableau_de_synthese_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau_de_synthese',
            name='class_type',
            field=models.CharField(choices=[('1st', 'Premiere 1'), ('2nd', 'Seconde 2')], max_length=50),
        ),
    ]
