# Generated by Django 3.1.6 on 2021-02-22 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.SlugField(choices=[('actualite', 'Actualite'), ('magazine', 'Magazine'), ('annouce', 'Annouce'), ('mines', 'Mines'), ('industries', 'Industries'), ('développement_technologique', 'Développement_Technologique'), ('blog_Post', 'Blog_Post'), ('draft', 'Draft')], default='draft', max_length=30)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
