# Generated by Django 3.1.6 on 2021-02-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210224_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SlugField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=30),
        ),
    ]
