# Generated by Django 3.1.6 on 2021-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210224_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('actualite', 'Actualite'), ('magazine', 'Magazine'), ('annouce', 'Annouce'), ('mines', 'Mines'), ('industries', 'Industries'), ('développement_Technologique', 'Developpement Technologique'), ('blog_Post', 'Blog Post')], default='actualite', max_length=50),
        ),
    ]
