# Generated by Django 3.1.6 on 2021-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('actualite', 'Actualite'), ('magazine', 'Magzi'), ('annouce', 'Anor'), ('mines', 'Mines'), ('industries', 'Industries'), ('développement_Technologique', 'Developpement Technologique'), ('blog_Post', 'Blog Post')], default='actualite', max_length=50),
        ),
    ]
