# Generated by Django 3.1.6 on 2021-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ED_Premiere_Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=20)),
                ('Semestre_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('inspecte', 'Inspecte'), ('non_inspecte', 'Non Inspecte')], default=None, max_length=50)),
                ('Denomination_ou_Raison_social', models.CharField(default=None, max_length=50)),
                ('Type_Dinstallatiion', models.CharField(default=None, max_length=50)),
                ('Localisation', models.CharField(default=None, max_length=50)),
                ('Adresse', models.CharField(default=None, max_length=50)),
                ('Inspecteurs', models.CharField(default=None, max_length=50)),
                ('Administration', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
